export const background = 'lightgrey'
export const surface = 'steelblue'
export const wireframe = 'darkgrey'
export const path = 'darkgrey'
export const selectedPath = 'blue'
export const pathOffset = 'darkblue'